# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgram/prgram.xci
# IP: The module: 'prgram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgram/prgram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgram/prgram.xci
# IP: The module: 'prgram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgram/prgram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'prgram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
