# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pipelineCPU.xdc

# IP: ip/pgrom/pgrom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==pgrom || ORIG_REF_NAME==pgrom} -quiet] -quiet
