# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/48946/Documents/GitHub/Computer-Organization-Project/pipelineCPU/pipelineCPU.srcs/sources_1/ip/pgrom/pgrom.xci
# IP: The module: 'pgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/48946/Documents/GitHub/Computer-Organization-Project/pipelineCPU/pipelineCPU.srcs/sources_1/ip/pgrom/pgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pgrom'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/48946/Documents/GitHub/Computer-Organization-Project/pipelineCPU/pipelineCPU.srcs/sources_1/ip/pgrom/pgrom.xci
# IP: The module: 'pgrom' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/48946/Documents/GitHub/Computer-Organization-Project/pipelineCPU/pipelineCPU.srcs/sources_1/ip/pgrom/pgrom_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pgrom'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
