# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir D:/Clone/Computer-Organization-Project/CPU/CPU.cache/wt [current_project]
set_property parent.project_path D:/Clone/Computer-Organization-Project/CPU/CPU.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo d:/Clone/Computer-Organization-Project/CPU/CPU.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/prgrom32.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgram/dmem32.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/test1ROM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgram/test1RAM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/test2ROM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/test4ROM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/test5ROM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgram/test5RAM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/test6ROM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgram/test6RAM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/test9ROM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/test12ROM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/BaseTest2ROM.coe
add_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/RUnitTestROM.coe
add_files d:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/BaseTest1ROM.coe
add_files d:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/InputTest.coe
add_files d:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/InputTest16.coe
read_verilog -library xil_defaultlib {
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/ALU.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/ClockDivider.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/Controller.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/DMem.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/Decoder.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/IFetch.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/InputModule.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/OutputModule.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/SegDisplay.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/SegGenerator.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/UartCommandParser.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/UartRx.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/UartTop.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/WriteBackMUX.v
  D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/new/top_module.v
}
read_ip -quiet D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgram/prgram.xci
set_property used_in_implementation false [get_files -all d:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgram/prgram_ooc.xdc]

read_ip -quiet D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/prgrom.xci
set_property used_in_implementation false [get_files -all d:/Clone/Computer-Organization-Project/CPU/CPU.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/constrs_1/new/constrains.xdc
set_property used_in_implementation false [get_files D:/Clone/Computer-Organization-Project/CPU/CPU.srcs/constrs_1/new/constrains.xdc]


synth_design -top top_module -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top_module.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb"
